swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /colas/cola/{cola}:
    delete:
      tags:
      - colas
      description: Borra la cola
      operationId: ColasController.BorrarCola
      parameters:
      - in: path
        name: cola
        description: Nombre de la cola a borrar
        required: true
        type: string
      responses:
        "200":
          description: '{string} Cola eliminada'
        "502":
          description: Error en borrado de cola
  /colas/crear/:
    post:
      tags:
      - colas
      description: Crea colas sqs
      operationId: ColasController.CrearCola
      parameters:
      - in: body
        name: body
        description: Configuración para la creación de la cola
        required: true
        schema:
          $ref: '#/definitions/models.Cola'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Colas'
        "403":
          description: body is empty
  /colas/mensajes:
    get:
      tags:
      - colas
      description: Lista hasta 10 mensajes en cola
      operationId: ColasController.RecibirMensajes
      parameters:
      - in: query
        name: nombre
        description: Nombre de la cola
        required: true
        type: string
      - in: query
        name: tiempoOculto
        description: El tiempo en segundos que un mensaje recibido se ocultará en la cola
        type: integer
        format: int64
      - in: query
        name: numMax
        description: Numero máximo de mensajes que se pueden recibir (1-10) Por defecto, su valor es 1
        type: integer
        format: int64
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Mensaje'
        "400":
          description: Error en parametros ingresados
    post:
      tags:
      - colas
      description: Borra la notificación de la cola según el key y el valor ingresados en el body
      operationId: ColasController.BorrarMensajeFiltro
      parameters:
      - in: body
        name: filtro
        description: Filtro de los mensajes a borrar
        required: true
        schema:
          $ref: '#/definitions/models.Filtro'
      responses:
        "200":
          description: '{string} Mensaje eliminado'
        "404":
          description: not found resource
  /colas/mensajes/{cola}:
    post:
      tags:
      - colas
      description: Borra la notificación de la cola
      operationId: ColasController.BorrarMensaje
      parameters:
      - in: path
        name: cola
        description: Nombre de la cola en donde está el mensaje
        required: true
        type: string
      - in: body
        name: mensaje
        description: Mensaje a borrar
        required: true
        schema:
          $ref: '#/definitions/models.Mensaje'
      responses:
        "200":
          description: '{string} Mensaje eliminado'
        "404":
          description: not found resource
  /colas/mensajes/espera:
    get:
      tags:
      - colas
      description: Espera por un tiempo determinado a que los mensajes estén disponibles y devuelve los recibidos en ese intervalo de tiempo
      operationId: ColasController.EsperarMensajes
      parameters:
      - in: query
        name: nombre
        description: Nombre de la cola
        required: true
        type: string
      - in: query
        name: tiempoEspera
        description: Tiempo de espera del api por mensajes
        required: true
        type: integer
        format: int64
      - in: query
        name: cantidad
        description: Cantidad máxima de mensajes a recibir. Esta cantidad debe ser menor a diez veces el tiempo de espera, ya que se pueden obtener máximo 10 mensajes por segundo. Por defecto, se recibirán todos
        type: integer
        format: int64
      - in: query
        name: filtro
        description: Recepción de mensajes filtrados por metadata. Tiene el funcionamiento de un and, por lo tanto sólo devuelve los valores que cumplan con todo el filtro
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Mensaje'
        "400":
          description: Error en parametros ingresados
  /colas/mensajes/usuario:
    get:
      tags:
      - colas
      description: Lista todos los mensajes de una cola por el identificador de un usuario
      operationId: ColasController.RecibirMensajesPorUsuario
      parameters:
      - in: query
        name: nombre
        description: Nombre de la cola
        required: true
        type: string
      - in: query
        name: usuario
        description: Identificador del usuario
        required: true
        type: string
      - in: query
        name: idMensaje
        description: Id del mensaje que requiera cambiar de estado a revisado
        type: string
      - in: query
        name: numRevisados
        description: Cantidad de mensajes revisados a recibir, seguidos de los mensajes pendientes. Por defecto se recibiran 5 si la cantidad de mensajes revisados es igual o mayor a este valor, de lo contrario se recibiran la cantidad de mensajes revisados disponibles. Para obtener todos, asignar el valor de -1
        type: integer
        format: int64
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Mensaje'
        "400":
          description: Error en parametros ingresados
  /email/enviar_email/:
    post:
      tags:
      - email
      description: Envia un correo a los destinatarios elegidos
      operationId: EnviarEmailController.PostSendEmail
      parameters:
      - in: body
        name: body
        description: Body de la inputicación
        required: true
        schema:
          $ref: '#/definitions/models.inputicacion'
      responses:
        "201":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
  /email/enviar_templated_email/:
    post:
      tags:
      - email
      description: Envia un correo con template a los destinatarios elegidos
      operationId: EnviarEmailController.PostSendTemplatedEmail
      parameters:
      - in: body
        name: body
        description: Body con los destinatarios y data
        required: true
        schema:
          $ref: '#/definitions/ses.SendBulkTemplatedEmailInput'
      responses:
        "201":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
  /notificaciones/enviar/:
    post:
      tags:
      - notificaciones
      description: Envía una notificación a cualquier suscriptor. La propiedad "Atributos" es opcional
      operationId: NotificacionController.PostOneNotif
      parameters:
      - in: body
        name: body
        description: Body de la notificación
        required: true
        schema:
          $ref: '#/definitions/models.Notificacion'
      responses:
        "201":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
  /notificaciones/suscribir/:
    post:
      tags:
      - notificaciones
      description: Suscribe cualquier tipo de endpoint a un topic
      operationId: NotificacionController.Subscribe
      parameters:
      - in: body
        name: body
        description: Body de la suscripcion
        required: true
        schema:
          $ref: '#/definitions/models.Suscripcion'
      - in: query
        name: atributos
        description: Atributos para filtrado de mensajes (atributo:valor, ...)
        type: string
      responses:
        "201":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
  /notificaciones/suscripcion/:
    post:
      tags:
      - notificaciones
      description: Verifica la suscripcion
      operationId: NotificacionController.VerifSus
      parameters:
      - in: body
        name: suscripcion
        description: Suscripcion a consultar
        required: true
        schema:
          $ref: '#/definitions/models.ConsultaSuscripcion'
      responses:
        "200":
          description: '{string} Mensaje eliminado'
        "404":
          description: not found resource
  /notificaciones/topic/:
    get:
      tags:
      - notificaciones
      description: Lista todos los ARN de los topics disponibles
      operationId: NotificacionController.GetTopics
      responses:
        "201":
          description: string,Status boolean,Message string,Data []string}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
    post:
      tags:
      - notificaciones
      description: Crea un topic en sns
      operationId: NotificacionController.CreateTopic
      parameters:
      - in: body
        name: body
        description: Body para configuracion del topic
        required: true
        schema:
          $ref: '#/definitions/models.Topic'
      responses:
        "201":
          description: string,Status boolean,Message string,Data []string }
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
    delete:
      tags:
      - notificaciones
      description: Borra el topic
      operationId: NotificacionController.BorrarTopic
      parameters:
      - in: query
        name: arnTopic
        description: Arn del topic a eliminar
        required: true
        type: string
      responses:
        "200":
          description: '{string} Topic eliminado'
        "404":
          description: not found resource
  /template_email/:
    get:
      tags:
      - template_email
      description: traer todos los template de aws ses
      operationId: EmailTemplateController.ListEmailTemplate
      parameters:
      - in: query
        name: nextToken
        description: posicion en la lista de una llamada previa
        type: string
      - in: query
        name: maxItems
        description: Numero máximo de mensajes que se pueden recibir (1-100) Por defecto, su valor es 10
        type: integer
        format: int64
      responses:
        "200":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
    put:
      tags:
      - template_email
      description: traer todos los template de aws ses
      operationId: EmailTemplateController.UpdateEmailTemplate
      parameters:
      - in: body
        name: body
        description: Body ses.UpdateTemplateInput struct
        required: true
        schema:
          $ref: '#/definitions/ses.UpdateTemplateInput'
      responses:
        "200":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
    post:
      tags:
      - template_email
      description: Crea un template para un correo personalizado
      operationId: EmailTemplateController.CreateEmailTemplate
      parameters:
      - in: body
        name: body
        description: Body ses.CreateTemplateInput struct
        required: true
        schema:
          $ref: '#/definitions/ses.CreateTemplateInput'
      responses:
        "201":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
  /template_email/{templateName}:
    get:
      tags:
      - template_email
      description: traer todos los template de aws ses
      operationId: EmailTemplateController.GetEmailTemplate
      parameters:
      - in: path
        name: templateName
        description: Nombre del template
        required: true
        type: string
      responses:
        "201":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "400":
          description: Error en parametros ingresados
    delete:
      tags:
      - template_email
      description: Borra el topic
      operationId: EmailTemplateController.DeleteEmailTemplate
      parameters:
      - in: path
        name: templateName
        description: Nombre del template a elimminar
        required: true
        type: string
      responses:
        "200":
          description: string,Status boolean,Message string,Data map[string]interface{}}
          schema:
            $ref: '#/definitions/map[string]interface{Success'
        "404":
          description: not found resource
definitions:
  1192.<nil>.string:
    title: string
    type: object
  7547.0xc000333ec0.false:
    title: "false"
    type: object
  8237.0xc000418060.false:
    title: "false"
    type: object
  8857.0xc000418240.false:
    title: "false"
    type: object
  map[string]interface{Success:
    title: map[string]interface{Success
    type: object
  models.Cola:
    title: Cola
    type: object
    properties:
      EsFifo:
        type: boolean
      EsperaVisibilidad:
        type: integer
        format: int64
      NombreCola:
        type: string
      Politica:
        $ref: '#/definitions/models.Politica'
      Retencion:
        type: integer
        format: int64
      Retraso:
        type: integer
        format: int64
      TamañoMaximo:
        type: integer
        format: int64
      TiempoEspera:
        type: integer
        format: int64
  models.Colas:
    title: Colas
    type: object
  models.ConsultaSuscripcion:
    title: ConsultaSuscripcion
    type: object
    properties:
      ArnTopic:
        type: string
      Endpoint:
        type: string
  models.Endpoint:
    title: Endpoint
    type: object
    properties:
      Atributos:
        type: array
        items:
          type: string
      Endpoint:
        type: string
      Id:
        type: string
      Protocolo:
        type: string
  models.Filtro:
    title: Filtro
    type: object
    properties:
      Filtro:
        $ref: '#/definitions/1192.<nil>.string'
      NombreCola:
        type: string
  models.Mensaje:
    title: Mensaje
    type: object
    properties:
      Attributes:
        additionalProperties:
          type: string
      Body:
        $ref: '#/definitions/7547.0xc000333ec0.false'
      ReceiptHandle:
        type: string
  models.Notificacion:
    title: Notificacion
    type: object
    properties:
      ArnTopic:
        type: string
      Asunto:
        type: string
      Atributos:
        $ref: '#/definitions/8237.0xc000418060.false'
      DestinatarioId:
        type: array
        items:
          type: string
      IdDeduplicacion:
        type: string
      IdGrupoMensaje:
        type: string
      Mensaje:
        type: string
      RemitenteId:
        type: string
  models.Politica:
    title: Politica
    type: object
    properties:
      Id:
        type: string
      Statement:
        type: array
        items:
          $ref: '#/definitions/8857.0xc000418240.false'
      Version:
        type: string
  models.Suscripcion:
    title: Suscripcion
    type: object
    properties:
      ArnTopic:
        type: string
      Suscritos:
        type: array
        items:
          $ref: '#/definitions/models.Endpoint'
  models.Topic:
    title: Topic
    type: object
    properties:
      Display:
        type: string
      EsFifo:
        type: boolean
      Nombre:
        type: string
  models.inputicacion:
    title: inputicacion
    type: object
  ses.CreateTemplateInput:
    title: CreateTemplateInput
    type: object
  ses.SendBulkTemplatedEmailInput:
    title: SendBulkTemplatedEmailInput
    type: object
  ses.UpdateTemplateInput:
    title: UpdateTemplateInput
    type: object
tags:
- name: notificaciones
  description: |
    NotificacionController operations for Notificacion
- name: colas
  description: |
    ColasController operations for Colas
- name: email
  description: |
    EnviarEmailController operations for inputicacion
- name: template_email
  description: |
    EnviarEmailController operations for inputicacion
